### PR TITLE
Update Jenkins to LTS v2.361.3

### PR DESCRIPTION
**Pull request by brianherrera**
Closes https://github.com/o3de/o3de-jenkins-pipeline/issues/26

This PR updates Jenkins to LTS v2.361.3 and updates plugins to latest. Jenkins requires Java 11 with this update. 

Tested changes on the sandbox and staging them in the main branch. Changes will be merged to the `o3de-prod` branch for deployment after our build nodes are upgraded to Java 11.

### CODE REVIEW

**Review by shirangj — APPROVED** [review]

**Comment by DMWeiss-divesIn** [comment]
Are the plugin updates solely needed for Jenkins LTS v2.361.3?  Are some updated because they are dependencies of updates needed for v2.361? And are those dependencies, also dependencies of other plugins?

**Comment by brianherrera** [comment]
> Are the plugin updates solely needed for Jenkins LTS v2.361.3? Are some updated because they are dependencies of updates needed for v2.361? And are those dependencies, also dependencies of other plugins?

It's a combination of updating our plugins to latest and updating the dependencies of other plugins.

**Comment by amzn-changml** [comment]
We may need to test the end to end workflow and some of the plugins once we update. It looks like there's a few restrictions for using Java 11 as noted here: https://www.jenkins.io/doc/administration/requirements/upgrade-java-guidelines/

**Comment by brianherrera** [comment]
> 



> We may need to test the end to end workflow and some of the plugins once we update. It looks like there's a few restrictions for using Java 11 as noted here: https://www.jenkins.io/doc/administration/requirements/upgrade-java-guidelines/

Agreed. Changes are staged in sandbox and will confirm pipeline works end to end prior to creating a PR to prod.

**Pull request merged**
